version: '3'

services:
  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./:/data

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/data
    depends_on:
      - spark

  trino:
    image: trinodb/trino:latest
    user: root  # Exécuter en tant que root pour éviter les problèmes de permission
    ports:
      - '8081:8080'
    volumes:
      - ./trino-config:/etc/trino
      - ./:/data
    depends_on:
      - spark

  jupyter:
    image: jupyter/all-spark-notebook:latest
    ports:
      - '8888:8888'
    volumes:
      - ./:/home/jovyan/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - spark
  superset:
    image: apache/superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=votre_clé_secrète_ici
    volumes:
      - ./superset_config:/app/superset_config
      - superset_home:/app/superset_home
    depends_on:
      - trino
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  superset_home:
